const celiacIngredients: string[] = [
  "Wheat",
  "Barley",
  "Rye",
  "Bulgur",
  "Couscous",
  "Farro",
  "Kamut",
  "Seitan",
  "Semolina",
  "Spelt",
  "Triticale",
  "Wheatberries",
  "Wheat bran",
  "Wheat germ",
  "Wheat starch",
  "Durum",
  "Einkorn wheat",
  "Emmer",
  "Farina",
  "Graham flour",
  "Rye flour",
  "Barley flour",
  "Malt",
  "Malt vinegar",
  "Malt extract",
  "Brewer's yeast",
];
export default celiacIngredients;
