import { Ingredient } from "./Ingredient";
import { IngredientCategory } from "./Categories";

export const celiacIngredients: Ingredient[] = [
  { name: "Wheat", category: IngredientCategory.DefinitelyAvoid },
  { name: "Barley", category: IngredientCategory.DefinitelyAvoid },
  { name: "Rye", category: IngredientCategory.DefinitelyAvoid },
  { name: "Bulgur", category: IngredientCategory.DefinitelyAvoid },
  { name: "Couscous", category: IngredientCategory.DefinitelyAvoid },
  { name: "Farro", category: IngredientCategory.DefinitelyAvoid },
  { name: "Kamut", category: IngredientCategory.DefinitelyAvoid },
  { name: "Seitan", category: IngredientCategory.DefinitelyAvoid },
  { name: "Semolina", category: IngredientCategory.DefinitelyAvoid },
  { name: "Spelt", category: IngredientCategory.DefinitelyAvoid },
  { name: "Triticale", category: IngredientCategory.DefinitelyAvoid },
  { name: "Wheatberries", category: IngredientCategory.DefinitelyAvoid },
  { name: "Wheat bran", category: IngredientCategory.DefinitelyAvoid },
  { name: "Wheat germ", category: IngredientCategory.DefinitelyAvoid },
  { name: "Wheat starch", category: IngredientCategory.DefinitelyAvoid },
  { name: "Durum", category: IngredientCategory.DefinitelyAvoid },
  { name: "Einkorn wheat", category: IngredientCategory.DefinitelyAvoid },
  { name: "Emmer", category: IngredientCategory.DefinitelyAvoid },
  { name: "Farina", category: IngredientCategory.DefinitelyAvoid },
  { name: "Graham flour", category: IngredientCategory.DefinitelyAvoid },
  { name: "Rye flour", category: IngredientCategory.DefinitelyAvoid },
  { name: "Barley flour", category: IngredientCategory.DefinitelyAvoid },
  { name: "Malt", category: IngredientCategory.DefinitelyAvoid },
  { name: "Malt vinegar", category: IngredientCategory.DefinitelyAvoid },
  { name: "Malt extract", category: IngredientCategory.DefinitelyAvoid },
  { name: "Brewer's yeast", category: IngredientCategory.DefinitelyAvoid },
  { name: "Oats", category: IngredientCategory.PotentiallyAvoid },
  { name: "Soy Sauce", category: IngredientCategory.PotentiallyAvoid },
  { name: "Licorice", category: IngredientCategory.PotentiallyAvoid },
  { name: "Beer", category: IngredientCategory.PotentiallyAvoid },
  { name: "Imitation Seafood", category: IngredientCategory.PotentiallyAvoid },
];
