import { Ingredient } from "./Ingredient";
import { IngredientCategory } from "./Categories";

export const vegetarianIngredients: Ingredient[] = [
  { name: "Chicken", category: IngredientCategory.DefinitelyAvoid },
  { name: "Fish", category: IngredientCategory.DefinitelyAvoid },
  { name: "Beef", category: IngredientCategory.DefinitelyAvoid },
  { name: "Pork", category: IngredientCategory.DefinitelyAvoid },
  { name: "Gelatin", category: IngredientCategory.DefinitelyAvoid },
  { name: "Shrimp", category: IngredientCategory.DefinitelyAvoid },
  { name: "Crab", category: IngredientCategory.DefinitelyAvoid },
  { name: "Lobster", category: IngredientCategory.DefinitelyAvoid },
  { name: "Mutton", category: IngredientCategory.DefinitelyAvoid },
  { name: "Duck", category: IngredientCategory.DefinitelyAvoid },
  { name: "Turkey", category: IngredientCategory.DefinitelyAvoid },
  { name: "Salmon", category: IngredientCategory.DefinitelyAvoid },
  { name: "Tuna", category: IngredientCategory.DefinitelyAvoid },
  { name: "Lamb", category: IngredientCategory.DefinitelyAvoid },
  { name: "Squid", category: IngredientCategory.DefinitelyAvoid },
  { name: "Octopus", category: IngredientCategory.DefinitelyAvoid },
  { name: "Venison", category: IngredientCategory.DefinitelyAvoid },
  { name: "Goat", category: IngredientCategory.DefinitelyAvoid },
  { name: "Quail", category: IngredientCategory.DefinitelyAvoid },
  { name: "Rabbit", category: IngredientCategory.DefinitelyAvoid },
  { name: "Bison", category: IngredientCategory.DefinitelyAvoid },
  { name: "Buffalo", category: IngredientCategory.DefinitelyAvoid },
  { name: "Sardines", category: IngredientCategory.DefinitelyAvoid },
  { name: "Anchovy", category: IngredientCategory.DefinitelyAvoid },
  { name: "Trout", category: IngredientCategory.DefinitelyAvoid },
  { name: "Cod", category: IngredientCategory.DefinitelyAvoid },
  { name: "Haddock", category: IngredientCategory.DefinitelyAvoid },
  { name: "Mackerel", category: IngredientCategory.DefinitelyAvoid },
  { name: "Oyster", category: IngredientCategory.DefinitelyAvoid },
  { name: "Clam", category: IngredientCategory.DefinitelyAvoid },
  { name: "Snail", category: IngredientCategory.DefinitelyAvoid },
  { name: "Frog leg", category: IngredientCategory.DefinitelyAvoid },
];
